In [2]:
pip install --upgrade pyDOE2

  Preparing metadata (setup.py) ... done
  Created wheel for pyDOE2: filename=pyDOE2-1.3.0-py3-none-any.whl size=25521 sha256=bebf8932abe52861932254b91f08f7ace00d6ac24d58ccae281d88f2b0b6c524
  Stored in directory: /root/.cache/pip/wheels/46/1f/29/6fda5c72f950841e39147ae603780ee913a62f977b4ad47ee4
Successfully built pyDOE2


In [7]:
from pyDOE2 import ccdesign


levels = 5


design = ccdesign(4, center=(1, 1), alpha='orthogonal')


# Print the design matrix
print("CCD Design Matrix:")
print(design)
design.shape


CCD Design Matrix:
[[-1.         -1.         -1.         -1.        ]
 [ 1.         -1.         -1.         -1.        ]
 [-1.          1.         -1.         -1.        ]
 [ 1.          1.         -1.         -1.        ]
 [-1.         -1.          1.         -1.        ]
 [ 1.         -1.          1.         -1.        ]
 [-1.          1.          1.         -1.        ]
 [ 1.          1.          1.         -1.        ]
 [-1.         -1.         -1.          1.        ]
 [ 1.         -1.         -1.          1.        ]
 [-1.          1.         -1.          1.        ]
 [ 1.          1.         -1.          1.        ]
 [-1.         -1.          1.          1.        ]
 [ 1.         -1.          1.          1.        ]
 [-1.          1.          1.          1.        ]
 [ 1.          1.          1.          1.        ]
 [ 0.          0.          0.          0.        ]
 [-2.05798302  0.          0.          0.        ]
 [ 2.05798302  0.          0.          0.        ]
 [ 0.       

(26, 4)

In [ ]:
import numpy as np
np.geomspace(1, 5, num=3, endpoint = True)

array([1.        , 2.23606798, 5.        ])

In [ ]:
np.geomspace(5, 10, num=3, endpoint = True)

array([ 5.        ,  7.07106781, 10.        ])

In [ ]:
np.geomspace(10, 15, num=3, endpoint = True)

array([10.        , 12.24744871, 15.        ])

In [ ]:
from pyDOE2 import ccdesign

# Define the number of levels for each factor
quantitative_levels = 3  # Number of levels for quantitative factors

# Convert quantitative_levels to integer
quantitative_levels = int(quantitative_levels)

# Generate the CCD design matrix
design = ccdesign(2, center=[quantitative_levels/2, quantitative_levels/2], alpha='orthogonal')

# Scale the design for quantitative factors
scaled_design = design.copy()
scaled_design[:, :2] = scaled_design[:, :2] * (quantitative_levels - 1)

# Define the levels for the qualitative factor
qualitative_levels = ['Low', 'High']

# Assign qualitative factor levels to the design
design_with_qualitative = scaled_design.copy()
design_with_qualitative[:, 2] = qualitative_levels

# Print the design matrix
print("CCD Design Matrix:")
print(design_with_qualitative)


TypeError: ignored

In [ ]:
% Define the factor levels and ranges
levels = 3; % Number of levels for each factor
factor_ranges = [1, 30; 1, 15; 1, 13]; % Range for each factor

% Generate the CCD design
design = fullfact([4 4 2]);

% Display the design matrix
disp('Full factorial Matrix:');
disp(design);

Matlab code since fullfact for python was not working :/